var dataset = [
[
    {
        "id":"scenario-0",
        "text":"<p>Introduction</p>",
        "img":"img/story-0/cover.PNG",
        "more":0,
        "info":"",
        "optNum":0,
        "optImg":0,
        "opt0":"Start",
        "target0":"scenario-1",
    },
    {
        "id":"scenario-1",
        "text":"<p>A local by-election is in 2 weeks. You are a voter but you don’t know who to vote for/ haven’t decided. Your friend tells you about Candidate X. You voted for him last time and was planning to vote for him again. But your friend’s WhatsApp message claims that Candidate X is guilty of domestic abuse. You are shocked! In disbelief! You cannot imagine this is true. You decide to investigate these claims.</p>",
        "img":"img/story-0/1.PNG",
        "more":0,
        "info":"",
        "optNum":0,
        "optImg":1,
        "opt0":"Next",
        "target0":"scenario-1-1",
    },
    {
        "id":"scenario-1-1",
        "text":"<p class='question'>What do you do next?</p>",
        "img":"img/story-0/1.PNG",
        "more":0,
        "info":"",
        "optNum":3,
        "optImg":0,
        "opt0":"Check your regular news sites",
        "target0":"scenario-2",
        "opt1":"Ask other friends",
        "target1":"scenario-stop",
        "opt2":"Call the elected official’s office",
        "target2":"scenario-stop",
        "opt3":"Check social media",
        "target3":"scenario-stop",
    },
    {
        "id":"scenario-2",
        "text":"<p>You share the articles you found with your friend to refute his claims that Candidate X beats his wife. In the articles you found, Candidate X says this is just campaign mud-slinging. In return, your friend sends you a special expose report from a news site that you don’t recognize with a headline that reads “Candidate X charged by High Court for domestic abuse”.</p><p class='question'>What do you do with the link?</p>",
        "img":"img/story-0/7.PNG",
        "more":0,
        "info":"",
        "optNum":2,
        "optImg":1,
        "opt0":"Click it",
        "target0":"scenario-3",
        "opt1":"Read the headline only and call it fake news",
        "target1":"scenario-stop",
        "opt2":"Ignore it/ Block your friend",
        "target2":"scenario-stop",
    },
    {
        "id":"scenario-3",
        "text":"<p>You realize that the article details how Candidate X has been accused of abusing his wife several times before. The article quotes family members of the victim and a reputable NGO - all of whom are saying  that Candidate X is very likely guilty. There is overwhelming evidence to prove this.</p><p class='question'>How do you feel having read this article?</p>",
        "img":"img/story-0/2.PNG",
        "more":0,
        "info":"",
        "optNum":2,
        "optImg":1,
        "opt0":"Angry - these are all lies!",
        "target0":"scenario-4",
        "opt1":"Confused - processing opposing views",
        "target1":"scenario-stop",
        "opt2":"Try to downplay its relevance",
        "target2":"scenario-stop",
    },
    {
        "id":"scenario-4",
        "text":"<p>You are so angry. You make a Facebook post about this issue. You even make the post public! You say in your post “Look at the lies these people are spreading about Candidate X! Trying to smear a hardworking representative” A couple hours later, you have a ton of comments. Most of your friends have commented agreeing with your statement. However there are some strangers who disagree, and have attached articles to their comments continuing to claim that Candidate X is guilty. These strangers also say that some of the commenters are cybertroopers and not to believe those comments.</p>",
        "img":"img/story-0/3.PNG",
        "more":0,
        "info":"",
        "optNum":0,
        "optImg":1,
        "opt0":"Next",
        "target0":"scenario-4-1",
    },
    {
        "id":"scenario-4-1",
        "text":"<p>You click on one of the profiles of the comments that someone says is made by a cybertrooper. You notice that their account is bare, not much personal info, and all their posts are only about Candidate X or others from the same political party.</p>",
        "img":"img/story-0/3.PNG",
        "more":0,
        "info":"",
        "optNum":0,
        "optImg":0,
        "opt0":"Next",
        "target0":"scenario-4-2",
    },
    {
        "id":"scenario-4-2",
        "text":"<p>The next morning, you find even more comments on your post and most of them are saying that the charges against Candidate X are true. There are even a few people who say that they themselves have been witnesses to his aggressive behaviour towards his wife.</p><p class='question'></>How do you feel now?</p>",
        "img":"img/story-0/3.PNG",
        "more":0,
        "info":"",
        "optNum":2,
        "optImg":0,
        "opt0":"Curious & willing to learn more",
        "target0":"scenario-stop",
        "opt1":"Even angier",
        "target1":"scenario-5",
        "opt2":"Withdrawn",
        "target2":"scenario-stop",
    },
    {
        "id":"scenario-5",
        "text":"<p class='question'>Do you feel like you got the whole story now?</p>",
        "img":"img/story-0/4.PNG",
        "more":0,
        "info":"",
        "optNum":1,
        "optImg":1,
        "opt0":"Yes, I have all the info I need",
        "target0":"scenario-6",
        "opt1":"No, I'm still learning new info about Candidate X",
        "target1":"scenario-6",
    },
    {
        "id":"scenario-6",
        "text":"<p>Are you compelled to visit these other news sites (Kini for example) again in the future?</p>",
        "img":"img/story-0/6.PNG",
        "more":0,
        "info":"",
        "optNum":1,
        "optImg":1,
        "opt0":"No",
        "target0":"scenario-7",
        "opt1":"Yes",
        "target1":"scenario-stop",
    },
    {
        "id":"scenario-7",
        "text":"<p class='question'>YOUR RESULTS</p><p>You are in an echo chamber. You are a dreamer. Here are tips to get out of your echo chamber. You should always have couple of these sites or information sources in your media diet so you can get alternative perspectives. Just having one type of news sites can lead you down the path of having just one perspective without realising there are others.</p>",
        "img":"img/story-0/5.PNG",
        "more":0,
        "info":"",
        "optNum":0,
        "optImg":1,
        "opt0":"The end",
        "target0":"scenario-end",
    },
    {
        "id":"scenario-end",
        "text":"",
        "endLinks":[
            "<a href='google.com' target='_blank'>Reference link 1</a>",
            "<a href='google.com' target='_blank'>Reference link 2</a>",
            "<a href='google.com' target='_blank'>Reference link 3</a>",
            "<a href='google.com' target='_blank'>Reference link 4</a>",
            "<a href='google.com' target='_blank'>Reference link 5</a>",
            "<a href='google.com' target='_blank'>Reference link 6</a>",
            "<a href='google.com' target='_blank'>Reference link 7</a>",
            "<a href='google.com' target='_blank'>Reference link 8</a>",
        ]
    }
]
];